#!/bin/bash
# Window defines this, use ${USERNAME:....} something instead
export HOMESFOLDER=C:/Users
export USERNAME=john
export GRAALJS=C:/graaljs-community-jvm-23.1.2-windows-amd64/graaljs-community-23.1.2-windows-amd64/bin/js.exe
export X3DJSONLD=..
export GRAALX3DJSONLD=..
export CLASSPATH=".;${X3DJSONLD}/java;${X3DJSONLD}/lib/X3DJSAIL.4.0.full.jar;${X3DJSONLD}/java;${X3DJSONLD}/lib/saxon-he-12.1.jar;${X3DJSONLD}/graaljs"
# GRAAL DOES NOT TAKE C:
export GRAAL_CLASSPATH=".;${X3DJSONLD}/java;${HOMESFOLDER}/$USERNAME/JSHumanoids/lib/X3DJSAIL.4.0.full.jar;${X3DJSONLD}/lib/saxon-he-12.1.jar;${X3DJSONLD}/graaljs"
export PYTHONPATH="{PYTHONPATH};C:\\Python311\\Lib;c:\\x3d-code\\www.web3d.org\\x3d\\stylesheets\\python"
export PATH="${JAVA_HOME}/bin:${JAVA_HOME}/jre/bin/server:${PATH}"

export PYTHON=py
export PIP=pip3
export NODE=node.exe
export NODEDIR=${HOMESFOLDER}/$USERNAME/JSHumanoids/node
# ${HOME}\\apache-maven-3.5.2\\bin\\mvn clean install
# sh replaceclass.sh
# ${HOME}\\apache-maven-3.5.2\\bin\\mvn install

function jjs() {
	# C:/graalvm-jdk-20_windows-x64_bin/graalvm-jdk-20.0.2+9.1/bin/js.cmd "$@"
	C:/graaljs-community-jvm-23.1.2-windows-amd64/graaljs-community-23.1.2-windows-amd64/bin/js.exe --experimental-options --polyglot --vm.Djs.allowAllAccess=true --vm.Xss1g --vm.Xmx4g --jvm --vm.classpath="${GRAAL_CLASSPATH}" "$@"
}

