#!/bin/bash
X3DJSONLD=C:/Users/john/jaminate/Jaminate/app/lib
SAXON=C:/Users/john/jaminate/Jaminate/app/lib
export CLASSPATH=".;${X3DJSONLD}/X3DJSAIL.4.0.full.jar;${SAXON}/saxon-he-12.1.jar"
export GRAAL_CLASSPATH=".;${X3DJSONLD}/X3DJSAIL.4.0.full.jar;${SAXON}/saxon-he-12.1.jar"
