mvn install:install-file -Dfile=lib/X3DJSAIL.4.0.full.jar -DgroupId=org.web3d.x3d -DartifactId=X3DJSAIL -Dversion=4.0.full -Dpackaging=jar
gradle clean build install run

# include X3DJSAIL a second time for VariationPhysicsModel
/c/graalvm-jdk-22_windows-x64_bin/graalvm-jdk-22+36.1/bin/javac.exe -Xlint:deprecation -cp "build/classes/java/main;lib/vecmath-1.5.2.jar;lib/X3DJSAIL.4.0.full.jar;lib/activation-1.1.1.jar;lib/tagsoup-1.2.1.jar;lib/graal/collections-24.0.0.jar;lib/graal/graaljs.jar;lib/graal/graaljs-launcher.jar;lib/graal/graaljs-scriptengine.jar;lib/graal/graal-sdk.jar;lib/graal/launcher-common.jar;lib/graal/nativeimage-24.0.0.jar;lib/graal/polyglot-24.0.0.jar;lib/graal/tregex.jar;lib/graal/truffle-api.jar;lib/graal/truffle-compiler-24.0.0.jar;lib/graal/truffle-icu4j.jar;lib/graal/truffle-runtime-24.0.0.jar;.;src/main/java" src/main/java/net/coderextreme/jaminate/*.java

# /c/graalvm-jdk-22_windows-x64_bin/graalvm-jdk-22+36.1/bin/java.exe -Xlint:deprecation -cp "build/classes/java/main;lib/X3DJSAIL.4.0.full.jar;build/install/app/lib/tagsoup-1.2.1.jar;lib/graal/collections-24.0.0.jar;lib/graal/graaljs.jar;lib/graal/graaljs-launcher.jar;lib/graal/graaljs-scriptengine.jar;lib/graal/graal-sdk.jar;lib/graal/launcher-common.jar;lib/graal/nativeimage-24.0.0.jar;lib/graal/polyglot-24.0.0.jar;lib/graal/tregex.jar;lib/graal/truffle-api.jar;lib/graal/truffle-compiler-24.0.0.jar;lib/graal/truffle-icu4j.jar;lib/graal/truffle-runtime-24.0.0.jar;." net.coderextreme.jaminate.JaminateBridge
     
# C:/graalvm-jdk-22_windows-x64_bin/graalvm-jdk-22+36.1/bin/java.exe -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -cp "build/classes/java/main;C:/Users/john/pythonSAI/X3DJSAIL.4.0.full.jar;build/install/app/lib/tagsoup-1.2.1.jar;lib/graal/collections-24.0.0.jar;lib/graal/graaljs.jar;lib/graal/graaljs-launcher.jar;lib/graal/graaljs-scriptengine.jar;lib/graal/graal-sdk.jar;lib/graal/launcher-common.jar;lib/graal/nativeimage-24.0.0.jar;lib/graal/polyglot-24.0.0.jar;lib/graal/tregex.jar;lib/graal/truffle-api.jar;lib/graal/truffle-compiler-24.0.0.jar;lib/graal/truffle-icu4j.jar;lib/graal/truffle-runtime-24.0.0.jar;." net.coderextreme.jaminate.JaminateBridge
